### ISSUE TITLE
NullPointerException when Anserini Solr Plugin given rtype=id

### ISSUE THREAD

**Issue by sujitpal** [elsevierlabs-os/anserini-solr-plugin#5]
Trace is as follows. This is caused by the query object in RerankedResult being set to null in the ResultReranker.java and then being serialized with toString in line AnseriniRequestHandler.java:109.

```
java.lang.NullPointerException at com.elsevier.asp.AnseriniRequestHandler.handleRequestBody(AnseriniRequestHandler.java:109) at
org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199) at 
org.apache.solr.core.SolrCore.execute(SolrCore.java:2578) at 
org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:780) at 
org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:566) at 
org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:423) at 
org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:350) at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602) at 
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540) at 
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) at 
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) at 
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at 
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) at 
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711) at 
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) at 
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347) at 
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) at 
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) at 
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678) at 
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) at 
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249) at 
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) at 
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220) 
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152) at 
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at 
org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335) at 
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at 
org.eclipse.jetty.server.Server.handle(Server.java:505) at 
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370) at 
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) at 
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) at 
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) at 
org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) at 
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) at 
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) at 
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) at 
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) at 
org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) at 
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781) at 
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917) at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sujitpal** [comment]
Since rtype=id is the same as no reranking, query_b is meaningless in this context, so fix is to render query_b only when rtype is not "id". Fix applied and tested, closing.
